service: boon-intermit-benefits

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  timeout: 10

  httpApi:
    authorizers:
      cognitoM2M:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${self:custom.userPoolId}
        audience:
          - ${self:custom.clientId}

  vpc:
    securityGroupIds:
      - sg-0e71e696efc0e5408
    subnetIds:
      - subnet-04df8373224263947
      - subnet-08c47a415c2dd886e

  environment:
    DB_HOST: boon-rds-dev.c2j6koy8871l.us-east-1.rds.amazonaws.com
    DB_NAME: boondb
    DB_SCHEMA: sinergy
    DB_USER: "{{resolve:secretsmanager:/boon/${sls:stage}/rds/credentials:SecretString:username}}"
    DB_PASSWORD: "{{resolve:secretsmanager:/boon/${sls:stage}/rds/credentials:SecretString:password}}"

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:CreateLogDelivery
            - logs:GetLogDelivery
            - logs:UpdateLogDelivery
            - logs:DeleteLogDelivery
            - logs:ListLogDeliveries
            - logs:PutResourcePolicy
            - logs:DescribeResourcePolicies
            - logs:DescribeLogGroups
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
          Resource: "*"

        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: "arn:aws:secretsmanager:us-east-1:*:secret:/boon/${sls:stage}/rds/*"

custom:
  userPoolId: us-east-1_d0MWO0QUB
  clientId: 6caav50hrviqc1eamamc54p7jv

functions:
  healthCheck:
    handler: src/handlers/public/health.handler
    events:
      - httpApi:
          path: /health
          method: get
    package:
      patterns:
        - "!**"
        - "src/handlers/public/health.js"

  newContractWebhook:
    handler: src/handlers/webhooks/new-contract.handler
    events:
      - httpApi:
          path: /integration/new-contract
          method: post
          authorizer:
            name: cognitoM2M
    package:
      patterns:
        - "!**"
        - "src/handlers/webhooks/new-contract.js"

  createEstipulante:
    handler: src/handlers/public/estipulante/create.handler
    events:
      - httpApi:
          path: /estipulante
          method: post
    package:
      patterns:
        - "!**"
        - "src/handlers/public/estipulante/create.js"
        - "src/classes/estipulante/estipulante.js"
        - "src/infra/database/postgres.js"
        - "node_modules/**"
        - "package.json"

  getEstipulante:
    handler: src/handlers/public/estipulante/get.handler
    events:
      - httpApi:
          path: /estipulante/{id}
          method: get
    package:
      patterns:
        - "!**"
        - "src/handlers/public/estipulante/get.js"
        - "src/classes/estipulante/estipulante.js"
        - "src/infra/database/postgres.js"
        - "node_modules/**"
        - "package.json"

  updateEstipulante:
    handler: src/handlers/public/estipulante/update.handler
    events:
      - httpApi:
          path: /estipulante/{id}
          method: put
    package:
      patterns:
        - "!**"
        - "src/handlers/public/estipulante/update.js"
        - "src/classes/estipulante/estipulante.js"
        - "src/infra/database/postgres.js"
        - "node_modules/**"
        - "package.json"

  deleteEstipulante:
    handler: src/handlers/public/estipulante/delete.handler
    events:
      - httpApi:
          path: /estipulante/{id}
          method: delete
    package:
      patterns:
        - "!**"
        - "src/handlers/public/estipulante/delete.js"
        - "src/classes/estipulante/estipulante.js"
        - "src/infra/database/postgres.js"
        - "node_modules/**"
        - "package.json"