ALTER TABLE "intermit-benefits".tb_beneficiario
ADD COLUMN logradouro VARCHAR(300),
ADD COLUMN numero VARCHAR(20),
ADD COLUMN complemento VARCHAR(100),
ADD COLUMN bairro VARCHAR(100),
ADD COLUMN cidade VARCHAR(100),
ADD COLUMN uf VARCHAR(2),
ADD COLUMN cep VARCHAR(9);